/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: samsidparty (https://sketchfab.com/samsidparty)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chevrolet-corvette-a1b738b341f44ad8829fd10d9da5e6ff
title: Chevrolet Corvette
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wheel_FR_Tyre_0: THREE.Mesh
    Wheel_FR_Rim_0: THREE.Mesh
    Wheel_FL_Tyre_0: THREE.Mesh
    Wheel_FL_Rim_0: THREE.Mesh
    Wheel_RR_Tyre_0: THREE.Mesh
    Wheel_RR_Rim_0: THREE.Mesh
    Wheel_RL_Tyre_0: THREE.Mesh
    Wheel_RL_Rim_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Black_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Interior_Aluminium_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Interior_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Mirror_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_WhitleLight_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_RedLight_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Carbon_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Carbon_0_1: THREE.Mesh
    Chevrolet_Corvette_LOD0_Paint_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Engine_Decals_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Carbon_Fiber_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Metal_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Seats_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Bolt_2_Interior_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Glass_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Aluminium_0: THREE.Mesh
    Chevrolet_Corvette_LOD0_Interior_Badge_0: THREE.Mesh
  }
  materials: {
    Tyre: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Interior_Aluminium: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    WhitleLight: THREE.MeshStandardMaterial
    RedLight: THREE.MeshStandardMaterial
    Carbon: THREE.MeshStandardMaterial
    Paint: THREE.MeshStandardMaterial
    Engine_Decals: THREE.MeshStandardMaterial
    Carbon_Fiber: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Seats: THREE.MeshStandardMaterial
    Bolt_2_Interior: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    Interior_Badge: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[93.3, 37.4, -144.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Wheel_FR_Tyre_0.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Wheel_FR_Rim_0.geometry} material={materials.material} />
          </group>
          <group position={[-93.3, 37.4, -144.8]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Wheel_FL_Tyre_0.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Wheel_FL_Rim_0.geometry} material={materials.material} />
          </group>
          <group position={[93, 39.25, 163.33]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 105, 105]}>
            <mesh geometry={nodes.Wheel_RR_Tyre_0.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Wheel_RR_Rim_0.geometry} material={materials.material} />
          </group>
          <group position={[-93, 39.14, 163.22]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[100, 105, 105]}>
            <mesh geometry={nodes.Wheel_RL_Tyre_0.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Wheel_RL_Rim_0.geometry} material={materials.material} />
          </group>
          <group position={[-40.17, 76.98, -46.4]} rotation={[-1.82, 0, 0]} scale={100}>
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Interior_Aluminium_0.geometry} material={materials.Interior_Aluminium} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Interior_0.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Mirror_0.geometry} material={materials.Mirror} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_WhitleLight_0.geometry} material={materials.WhitleLight} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_RedLight_0.geometry} material={materials.RedLight} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Carbon_0_1.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Paint_0.geometry} material={materials.Paint} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Engine_Decals_0.geometry} material={materials.Engine_Decals} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Carbon_Fiber_0.geometry} material={materials.Carbon_Fiber} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Seats_0.geometry} material={materials.Seats} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Bolt_2_Interior_0.geometry} material={materials.Bolt_2_Interior} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Aluminium_0.geometry} material={materials.Aluminium} />
            <mesh geometry={nodes.Chevrolet_Corvette_LOD0_Interior_Badge_0.geometry} material={materials.Interior_Badge} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
